CREATE TABLE `content_archive` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`format` varchar(32),
	`platform` varchar(32),
	`language` varchar(64) NOT NULL,
	`cefrLevel` varchar(4),
	`hook` text,
	`concept` text,
	`script` text,
	`vocabTaught` json,
	`inspiredByCreator` varchar(128),
	`hashtags` json,
	`viralPotential` text,
	`status` varchar(32) DEFAULT 'idea',
	`publishedUrl` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_archive_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `creator_knowledge` (
	`id` int AUTO_INCREMENT NOT NULL,
	`creatorName` varchar(128) NOT NULL,
	`handle` varchar(128),
	`platform` varchar(32),
	`airtableRecordId` varchar(32),
	`language` varchar(64),
	`region` varchar(128),
	`contentType` varchar(32),
	`teachingMethods` json,
	`musicStyles` json,
	`topicsTeught` json,
	`slangContributed` json,
	`contentIdeas` json,
	`lessonsGenerated` int DEFAULT 0,
	`songsGenerated` int DEFAULT 0,
	`contentGenerated` int DEFAULT 0,
	`lastScrapedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creator_knowledge_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cultural_knowledge` (
	`id` int AUTO_INCREMENT NOT NULL,
	`topic` varchar(255) NOT NULL,
	`category` varchar(64),
	`language` varchar(64) NOT NULL,
	`region` varchar(128),
	`description` text NOT NULL,
	`relatedVocab` json,
	`imagePrompt` text,
	`sourceCreator` varchar(128),
	`sourceUrl` varchar(512),
	`cefrLevel` varchar(4),
	`isVerified` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cultural_knowledge_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lesson_archive` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`language` varchar(64) NOT NULL,
	`dialect` varchar(64),
	`cefrLevel` varchar(4) NOT NULL,
	`category` varchar(64),
	`topic` varchar(255),
	`culturalContext` text,
	`exercises` json,
	`vocabTaught` json,
	`creatorMethodsUsed` json,
	`inspiredByCreators` json,
	`totalXP` int DEFAULT 0,
	`timesServed` int DEFAULT 0,
	`avgScore` int,
	`qualityRating` int,
	`status` varchar(32) DEFAULT 'generated',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lesson_archive_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `slang_vault` (
	`id` int AUTO_INCREMENT NOT NULL,
	`word` varchar(255) NOT NULL,
	`pronunciation` varchar(255),
	`language` varchar(64) NOT NULL,
	`dialect` varchar(64),
	`region` varchar(128),
	`meaning` text NOT NULL,
	`alternativeMeanings` json,
	`formality` varchar(32),
	`usageContext` text,
	`exampleSentence` text,
	`exampleTranslation` text,
	`warningNote` text,
	`sourceCreator` varchar(128),
	`sourceUrl` varchar(512),
	`isVerified` int DEFAULT 0,
	`freshness` varchar(16) DEFAULT 'current',
	`trendScore` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `slang_vault_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `song_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleEnglish` varchar(255),
	`language` varchar(64) NOT NULL,
	`dialect` varchar(64),
	`genre` varchar(128),
	`mood` varchar(128),
	`tempo` varchar(32),
	`cefrLevel` varchar(4),
	`lyrics` text,
	`lyricsTranslation` text,
	`vocabTaught` json,
	`sunoPrompt` text,
	`sunoTags` varchar(512),
	`audioUrl` varchar(512),
	`audioUrl2` varchar(512),
	`sunoJobId` varchar(128),
	`inspiredByCreator` varchar(128),
	`musicStyle` varchar(128),
	`teachingNotes` text,
	`isEntertainmentOnly` int DEFAULT 0,
	`status` varchar(32) DEFAULT 'generated',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `song_library_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `translation_archive` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceText` text NOT NULL,
	`translatedText` text NOT NULL,
	`sourceLanguage` varchar(64) NOT NULL,
	`targetLanguage` varchar(64) NOT NULL,
	`targetDialect` varchar(64),
	`translationType` varchar(32),
	`slangUsed` json,
	`culturalNotes` text,
	`dialectVariants` json,
	`qualityScore` int,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `translation_archive_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vocab_bank` (
	`id` int AUTO_INCREMENT NOT NULL,
	`word` varchar(255) NOT NULL,
	`pronunciation` varchar(255),
	`meaning` text NOT NULL,
	`partOfSpeech` varchar(32),
	`language` varchar(64) NOT NULL,
	`dialect` varchar(64),
	`region` varchar(128),
	`cefrLevel` varchar(4),
	`category` varchar(64),
	`exampleSentence` text,
	`exampleTranslation` text,
	`culturalNote` text,
	`imagePrompt` text,
	`audioUrl` varchar(512),
	`sourceCreator` varchar(128),
	`sourceUrl` varchar(512),
	`isSlang` int DEFAULT 0,
	`isVerified` int DEFAULT 0,
	`freshness` varchar(16) DEFAULT 'current',
	`timesUsedInLessons` int DEFAULT 0,
	`timesUsedInSongs` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vocab_bank_id` PRIMARY KEY(`id`)
);
