/**
 * Call Scorecard Screen
 * Boxing-style round-by-round grading after each Coach Mode call.
 * Scores: Pronunciation, Comprehension, Fluency, Vocabulary, Recovery.
 * Feeds weak areas back to the teacher/coach for adaptive follow-up.
 */
import React, { useState } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Platform,
} from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import * as Haptics from "expo-haptics";

const Colors = {
  bg: "#0A0E1A",
  card: "#141B2D",
  cardBorder: "#1E293B",
  text: "#FFFFFF",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  primary: "#00AAFF",
  warning: "#F59E0B",
  success: "#10B981",
  error: "#EF4444",
  purple: "#8B5CF6",
  orange: "#F97316",
  gold: "#FFD700",
  pink: "#EC4899",
  teal: "#14B8A6",
};

interface ScoreCategory {
  id: string;
  name: string;
  score: number; // 0-100
  icon: string;
  color: string;
  details: string[];
  flaggedItems: string[];
  improvement: string;
}

// Simulated scorecard data (in production, generated by AI analysis of the call)
const SCORECARD: ScoreCategory[] = [
  {
    id: "pronunciation",
    name: "Pronunciation",
    score: 72,
    icon: "mic",
    color: Colors.orange,
    details: [
      "Clear vowel sounds on basic words",
      "Good rhythm and intonation on greetings",
      "Struggled with rolled 'rr' in 'perro' and 'carro'",
      "Soft 'd' between vowels needs work",
    ],
    flaggedItems: ["perro (said 'pero')", "carro (flat 'r')", "ciudad (skipped soft 'd')", "entonces (stress on wrong syllable)"],
    improvement: "Practice rolled 'rr' with tongue exercises. Listen to native speakers say these words 10x each.",
  },
  {
    id: "comprehension",
    name: "Comprehension",
    score: 85,
    icon: "ear",
    color: Colors.primary,
    details: [
      "Understood 17 of 20 questions correctly",
      "Handled fast speech well on familiar topics",
      "Asked for 2 repeats (appropriate, not excessive)",
      "Missed meaning when speaker used slang 'vale'",
    ],
    flaggedItems: ["'¿Me puedes dar una mano?' — didn't recognize idiom", "'Vale' — confused with 'valley'", "'No entiendo' triggered 2 times"],
    improvement: "Study common idioms and colloquial expressions. The phrase 'dar una mano' means 'give a hand/help'.",
  },
  {
    id: "fluency",
    name: "Fluency",
    score: 68,
    icon: "water",
    color: Colors.teal,
    details: [
      "Average response time: 3.2 seconds (target: <2s)",
      "Used 4 filler words ('um', 'eh') in 8 minutes",
      "2 long pauses (>5 seconds) while forming sentences",
      "Good flow on practiced phrases, hesitant on new constructions",
    ],
    flaggedItems: ["5.8s pause before past tense sentence", "4.2s pause when asked unexpected question", "'Um' used 4 times", "'Eh' used as filler"],
    improvement: "Practice speaking without pausing. Use simple sentences first, then build complexity. Record yourself daily for 2 minutes.",
  },
  {
    id: "vocabulary",
    name: "Vocabulary Range",
    score: 78,
    icon: "book",
    color: Colors.purple,
    details: [
      "Used 34 unique words during the call",
      "Attempted 3 new words not yet in your deck",
      "Correctly used 8 of 10 target verbs",
      "Relied heavily on 'tener' and 'ser' (diversify!)",
    ],
    flaggedItems: ["Over-used 'tener' (6 times, try 'poseer', 'contar con')", "Missed opportunity to use 'hacer falta'", "Said 'bueno' 5 times as filler"],
    improvement: "This week, focus on using 'poder', 'deber', and 'hacer falta' instead of defaulting to 'tener' for everything.",
  },
  {
    id: "recovery",
    name: "Recovery",
    score: 90,
    icon: "shield-checkmark",
    color: Colors.success,
    details: [
      "Handled confusion gracefully — asked for clarification politely",
      "Used 'Puede repetir, por favor?' correctly",
      "Didn't freeze when lost — attempted paraphrasing",
      "Recovered from pronunciation error by self-correcting",
    ],
    flaggedItems: ["One moment of silence where you could have asked for help"],
    improvement: "Excellent recovery skills! Keep using clarification phrases. Next: try 'No me queda claro' for variety.",
  },
];

const CALL_SUMMARY = {
  callTitle: "Meeting Your Host Family",
  speaker: "Familia Rodriguez",
  duration: "12 min 34 sec",
  date: "May 23, 2026",
  overallScore: 79,
  overallGrade: "B+",
  xpEarned: 150,
  paceCredit: "1.5x",
  totalWords: 187,
  uniqueWords: 34,
  noEntiendoCount: 2,
  selfCorrections: 3,
};

const COACH_NOTES = [
  { priority: "high", note: "Pronunciation of 'rr' sounds is your biggest weakness right now. 15 min daily drill prescribed." },
  { priority: "high", note: "Response time needs to drop below 2 seconds. Try thinking in Spanish, not translating from English." },
  { priority: "medium", note: "Diversify your verb usage — you're relying too much on 'tener' and 'ser'." },
  { priority: "low", note: "Great recovery skills! You handle confusion like a natural. Keep it up." },
];

const PRESCRIBED_DRILLS = [
  { title: "Rolled 'RR' Practice", type: "pronunciation", duration: "10 min", priority: "high", route: "/pronunciation-drill", params: { word: "perro,carro,arriba,tierra,correo", category: "Rolled RR" } },
  { title: "Speed Response Drill", type: "fluency", duration: "8 min", priority: "high", route: "/conversation-sim", params: { scenario: "speed-response", difficulty: "hard" } },
  { title: "Verb Variety Challenge", type: "vocabulary", duration: "12 min", priority: "medium", route: "/flashcard-review", params: { filter: "verbs", category: "Verb Variety" } },
  { title: "Idiom Flashcards", type: "comprehension", duration: "5 min", priority: "medium", route: "/flashcard-review", params: { filter: "idioms", category: "Idioms" } },
];

export default function CallScorecardScreen() {
  const [expandedCategory, setExpandedCategory] = useState<string | null>("pronunciation");

  const getScoreColor = (score: number) => {
    if (score >= 90) return Colors.success;
    if (score >= 75) return Colors.primary;
    if (score >= 60) return Colors.warning;
    return Colors.error;
  };

  const getGradeEmoji = (grade: string) => {
    if (grade.startsWith("A")) return "🏆";
    if (grade.startsWith("B")) return "💪";
    if (grade.startsWith("C")) return "📈";
    return "🎯";
  };

  return (
    <ScreenContainer edges={["top", "left", "right"]}>
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={22} color={Colors.text} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Call Scorecard</Text>
          <TouchableOpacity style={styles.shareBtn}>
            <Ionicons name="share-outline" size={20} color={Colors.primary} />
          </TouchableOpacity>
        </View>

        {/* Overall Score Card */}
        <View style={styles.overallCard}>
          <View style={styles.overallTop}>
            <View style={styles.gradeCircle}>
              <Text style={styles.gradeEmoji}>{getGradeEmoji(CALL_SUMMARY.overallGrade)}</Text>
              <Text style={styles.gradeText}>{CALL_SUMMARY.overallGrade}</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.callTitle}>{CALL_SUMMARY.callTitle}</Text>
              <Text style={styles.callSpeaker}>with {CALL_SUMMARY.speaker}</Text>
              <Text style={styles.callDate}>{CALL_SUMMARY.date} • {CALL_SUMMARY.duration}</Text>
            </View>
          </View>

          <View style={styles.overallScoreRow}>
            <View style={styles.overallScoreItem}>
              <Text style={[styles.overallScoreValue, { color: getScoreColor(CALL_SUMMARY.overallScore) }]}>
                {CALL_SUMMARY.overallScore}
              </Text>
              <Text style={styles.overallScoreLabel}>Overall</Text>
            </View>
            <View style={styles.overallDivider} />
            <View style={styles.overallScoreItem}>
              <Text style={styles.overallScoreValue}>{CALL_SUMMARY.xpEarned}</Text>
              <Text style={styles.overallScoreLabel}>XP Earned</Text>
            </View>
            <View style={styles.overallDivider} />
            <View style={styles.overallScoreItem}>
              <Text style={[styles.overallScoreValue, { color: Colors.gold }]}>{CALL_SUMMARY.paceCredit}</Text>
              <Text style={styles.overallScoreLabel}>Pace Credit</Text>
            </View>
          </View>

          {/* Quick Stats */}
          <View style={styles.quickStats}>
            <View style={styles.quickStatItem}>
              <Text style={styles.quickStatValue}>{CALL_SUMMARY.totalWords}</Text>
              <Text style={styles.quickStatLabel}>Words spoken</Text>
            </View>
            <View style={styles.quickStatItem}>
              <Text style={styles.quickStatValue}>{CALL_SUMMARY.uniqueWords}</Text>
              <Text style={styles.quickStatLabel}>Unique words</Text>
            </View>
            <View style={styles.quickStatItem}>
              <Text style={styles.quickStatValue}>{CALL_SUMMARY.noEntiendoCount}</Text>
              <Text style={styles.quickStatLabel}>"No entiendo"</Text>
            </View>
            <View style={styles.quickStatItem}>
              <Text style={styles.quickStatValue}>{CALL_SUMMARY.selfCorrections}</Text>
              <Text style={styles.quickStatLabel}>Self-corrections</Text>
            </View>
          </View>
        </View>

        {/* Score Categories (Boxing Rounds) */}
        <Text style={styles.sectionTitle}>Round-by-Round Breakdown</Text>
        {SCORECARD.map((cat) => {
          const expanded = expandedCategory === cat.id;
          return (
            <TouchableOpacity
              key={cat.id}
              style={[styles.categoryCard, expanded && styles.categoryCardExpanded]}
              onPress={() => {
                setExpandedCategory(expanded ? null : cat.id);
                if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
              }}
              activeOpacity={0.8}
            >
              {/* Category Header */}
              <View style={styles.catHeader}>
                <View style={[styles.catIconWrap, { backgroundColor: cat.color + "15" }]}>
                  <Ionicons name={cat.icon as any} size={18} color={cat.color} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.catName}>{cat.name}</Text>
                </View>
                <View style={styles.catScoreWrap}>
                  <Text style={[styles.catScore, { color: getScoreColor(cat.score) }]}>{cat.score}</Text>
                  <Text style={styles.catScoreMax}>/100</Text>
                </View>
                <Ionicons
                  name={expanded ? "chevron-up" : "chevron-down"}
                  size={16}
                  color={Colors.textMuted}
                />
              </View>

              {/* Score Bar */}
              <View style={styles.catBarOuter}>
                <View style={[styles.catBarFill, { width: `${cat.score}%`, backgroundColor: getScoreColor(cat.score) }]} />
              </View>

              {/* Expanded Details */}
              {expanded && (
                <View style={styles.catExpanded}>
                  {/* What went well / needs work */}
                  <Text style={styles.catSubTitle}>Performance Notes</Text>
                  {cat.details.map((d, i) => (
                    <View key={i} style={styles.detailItem}>
                      <Ionicons
                        name={i < 2 ? "checkmark-circle" : "alert-circle"}
                        size={13}
                        color={i < 2 ? Colors.success : Colors.warning}
                      />
                      <Text style={styles.detailText}>{d}</Text>
                    </View>
                  ))}

                  {/* Flagged Items */}
                  {cat.flaggedItems.length > 0 && (
                    <>
                      <Text style={styles.catSubTitle}>Flagged Items</Text>
                      {cat.flaggedItems.map((f, i) => (
                        <View key={i} style={styles.flagItem}>
                          <Ionicons name="flag" size={12} color={Colors.error} />
                          <Text style={styles.flagText}>{f}</Text>
                        </View>
                      ))}
                    </>
                  )}

                  {/* Coach Prescription */}
                  <View style={styles.prescriptionBox}>
                    <Ionicons name="fitness" size={14} color={Colors.gold} />
                    <Text style={styles.prescriptionText}>{cat.improvement}</Text>
                  </View>
                </View>
              )}
            </TouchableOpacity>
          );
        })}

        {/* Coach's Notes */}
        <Text style={styles.sectionTitle}>Coach's Analysis</Text>
        <View style={styles.coachNotesCard}>
          <View style={styles.coachHeader}>
            <View style={styles.coachAvatarSmall}>
              <Ionicons name="school" size={18} color={Colors.gold} />
            </View>
            <Text style={styles.coachLabel}>Coach Sophia's Notes</Text>
          </View>
          {COACH_NOTES.map((note, idx) => (
            <View key={idx} style={styles.noteItem}>
              <View style={[
                styles.notePriority,
                { backgroundColor: note.priority === "high" ? Colors.error + "20" : note.priority === "medium" ? Colors.warning + "20" : Colors.success + "20" }
              ]}>
                <Text style={[
                  styles.notePriorityText,
                  { color: note.priority === "high" ? Colors.error : note.priority === "medium" ? Colors.warning : Colors.success }
                ]}>
                  {note.priority.toUpperCase()}
                </Text>
              </View>
              <Text style={styles.noteText}>{note.note}</Text>
            </View>
          ))}
        </View>

        {/* Prescribed Drills */}
        <Text style={styles.sectionTitle}>Prescribed Drills</Text>
        <Text style={styles.sectionSub}>Complete these before your next call</Text>
        {PRESCRIBED_DRILLS.map((drill, idx) => (
          <View key={idx} style={styles.drillCard}>
            <View style={{ flex: 1 }}>
              <Text style={styles.drillTitle}>{drill.title}</Text>
              <View style={styles.drillMeta}>
                <Text style={styles.drillType}>{drill.type}</Text>
                <Text style={styles.drillDuration}>{drill.duration}</Text>
              </View>
            </View>
            <TouchableOpacity
              style={[
                styles.drillBtn,
                { backgroundColor: drill.priority === "high" ? Colors.error + "15" : Colors.primary + "15" }
              ]}
              activeOpacity={0.8}
              onPress={() => {
                if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                router.push({ pathname: drill.route as any, params: drill.params });
              }}
            >
              <Text style={[
                styles.drillBtnText,
                { color: drill.priority === "high" ? Colors.error : Colors.primary }
              ]}>
                Start
              </Text>
            </TouchableOpacity>
          </View>
        ))}

        {/* Next Call Preview */}
        <View style={styles.nextCallCard}>
          <Ionicons name="call" size={20} color={Colors.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.nextCallTitle}>Next Call: Surprise Review</Text>
            <Text style={styles.nextCallSub}>
              Based on today's results, Coach Sophia is scheduling a follow-up call focused on pronunciation and fluency. Be ready — it could come anytime.
            </Text>
          </View>
        </View>

        {/* Pronunciation Heat Map CTA */}
        <TouchableOpacity
          onPress={() => router.push({ pathname: "/pronunciation-heat-map" as any, params: { source: "call" } })}
          style={{ flexDirection: "row", alignItems: "center", backgroundColor: Colors.primary + "15", padding: 14, borderRadius: 12, marginTop: 12, gap: 10 }}
        >
          <Ionicons name="flame" size={22} color={Colors.primary} />
          <View style={{ flex: 1 }}>
            <Text style={{ fontSize: 14, fontWeight: "600", color: Colors.text }}>View Pronunciation Heat Map</Text>
            <Text style={{ fontSize: 11, color: Colors.textMuted, marginTop: 2 }}>See which sounds you nail vs. struggle with</Text>
          </View>
          <Ionicons name="chevron-forward" size={18} color={Colors.textMuted} />
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  content: { padding: 20 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 18, fontWeight: "700", color: Colors.text },
  shareBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.card,
    alignItems: "center",
    justifyContent: "center",
  },

  overallCard: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.gold + "30",
  },
  overallTop: { flexDirection: "row", gap: 14, marginBottom: 16 },
  gradeCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.gold + "15",
    alignItems: "center",
    justifyContent: "center",
  },
  gradeEmoji: { fontSize: 18 },
  gradeText: { fontSize: 14, fontWeight: "800", color: Colors.gold },
  callTitle: { fontSize: 16, fontWeight: "700", color: Colors.text },
  callSpeaker: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  callDate: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },

  overallScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: Colors.bg,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 14,
  },
  overallScoreItem: { alignItems: "center" },
  overallScoreValue: { fontSize: 20, fontWeight: "800", color: Colors.text },
  overallScoreLabel: { fontSize: 10, color: Colors.textMuted, marginTop: 2 },
  overallDivider: { width: 1, height: 28, backgroundColor: Colors.cardBorder },

  quickStats: { flexDirection: "row", justifyContent: "space-between" },
  quickStatItem: { alignItems: "center" },
  quickStatValue: { fontSize: 16, fontWeight: "700", color: Colors.text },
  quickStatLabel: { fontSize: 9, color: Colors.textMuted, marginTop: 2 },

  sectionTitle: { fontSize: 16, fontWeight: "700", color: Colors.text, marginBottom: 4 },
  sectionSub: { fontSize: 12, color: Colors.textMuted, marginBottom: 12 },

  categoryCard: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  categoryCardExpanded: { borderColor: Colors.primary + "40" },
  catHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  catIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  catName: { fontSize: 14, fontWeight: "600", color: Colors.text },
  catScoreWrap: { flexDirection: "row", alignItems: "baseline", marginRight: 8 },
  catScore: { fontSize: 18, fontWeight: "800" },
  catScoreMax: { fontSize: 11, color: Colors.textMuted },
  catBarOuter: { height: 6, borderRadius: 3, backgroundColor: Colors.cardBorder },
  catBarFill: { height: 6, borderRadius: 3 },

  catExpanded: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: Colors.cardBorder },
  catSubTitle: { fontSize: 12, fontWeight: "700", color: Colors.textSecondary, marginBottom: 6, marginTop: 10 },
  detailItem: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginBottom: 5 },
  detailText: { flex: 1, fontSize: 12, color: Colors.textSecondary, lineHeight: 17 },
  flagItem: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginBottom: 4 },
  flagText: { flex: 1, fontSize: 11, color: Colors.error, lineHeight: 16 },
  prescriptionBox: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: Colors.gold + "10",
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
    borderLeftWidth: 3,
    borderLeftColor: Colors.gold,
  },
  prescriptionText: { flex: 1, fontSize: 11, color: Colors.textSecondary, lineHeight: 16 },

  coachNotesCard: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: Colors.gold + "25",
  },
  coachHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  coachAvatarSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.gold + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  coachLabel: { fontSize: 13, fontWeight: "700", color: Colors.gold },
  noteItem: { flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 10 },
  notePriority: { borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2 },
  notePriorityText: { fontSize: 9, fontWeight: "800" },
  noteText: { flex: 1, fontSize: 12, color: Colors.textSecondary, lineHeight: 17 },

  drillCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  drillTitle: { fontSize: 13, fontWeight: "600", color: Colors.text },
  drillMeta: { flexDirection: "row", gap: 10, marginTop: 3 },
  drillType: { fontSize: 11, color: Colors.primary, textTransform: "capitalize" },
  drillDuration: { fontSize: 11, color: Colors.textMuted },
  drillBtn: { borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  drillBtnText: { fontSize: 12, fontWeight: "700" },

  nextCallCard: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: Colors.primary + "10",
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: Colors.primary + "30",
  },
  nextCallTitle: { fontSize: 13, fontWeight: "700", color: Colors.primary },
  nextCallSub: { fontSize: 11, color: Colors.textSecondary, marginTop: 4, lineHeight: 16 },
});
