/**
 * Post-Conversation Feedback Report
 * Comprehensive AI-generated analysis after every teacher/AI call.
 * Features: Radar chart, mistake breakdown, vocabulary learned, suggested next practice.
 * Inspired by Fluently App's post-call reports but way more detailed.
 */
import React, { useState, useEffect, useRef } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Animated,
  Platform,
  Dimensions,
  FlatList,
} from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import * as Haptics from "expo-haptics";
import AsyncStorage from "@react-native-async-storage/async-storage";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

// ─── TYPES ──────────────────────────────────────────────────────────────────

interface SkillScore {
  id: string;
  name: string;
  score: number;
  previousScore: number;
  icon: string;
  color: string;
}

interface MistakeEntry {
  id: string;
  type: "grammar" | "pronunciation" | "vocabulary" | "fluency";
  whatYouSaid: string;
  correction: string;
  explanation: string;
  severity: "minor" | "moderate" | "critical";
}

interface VocabLearned {
  id: string;
  word: string;
  translation: string;
  pronunciation: string;
  context: string;
  saved: boolean;
}

interface PracticeRecommendation {
  id: string;
  title: string;
  description: string;
  type: string;
  duration: string;
  priority: "high" | "medium" | "low";
  icon: string;
  route: string;
}

interface ConversationHighlight {
  timestamp: string;
  type: "great" | "struggle" | "breakthrough";
  text: string;
  note: string;
}

// ─── MOCK DATA (In production, generated by AI after each call) ──────────────

const SKILL_SCORES: SkillScore[] = [
  { id: "pronunciation", name: "Pronunciation", score: 74, previousScore: 68, icon: "mic", color: "#F97316" },
  { id: "grammar", name: "Grammar", score: 82, previousScore: 79, icon: "create", color: "#8B5CF6" },
  { id: "vocabulary", name: "Vocabulary", score: 71, previousScore: 65, icon: "book", color: "#06B6D4" },
  { id: "fluency", name: "Fluency", score: 66, previousScore: 63, icon: "water", color: "#14B8A6" },
  { id: "comprehension", name: "Listening", score: 88, previousScore: 85, icon: "ear", color: "#3B82F6" },
  { id: "confidence", name: "Confidence", score: 79, previousScore: 72, icon: "shield-checkmark", color: "#10B981" },
];

const MISTAKES: MistakeEntry[] = [
  {
    id: "1", type: "grammar",
    whatYouSaid: "Yo soy tengo hambre",
    correction: "Yo tengo hambre",
    explanation: "Don't use 'soy' with 'tener'. 'Tener hambre' already means 'to be hungry' — no extra 'ser' needed.",
    severity: "moderate",
  },
  {
    id: "2", type: "pronunciation",
    whatYouSaid: "pero (with flat r)",
    correction: "perro (rolled rr)",
    explanation: "Single 'r' = soft tap. Double 'rr' = rolled/trilled. 'Pero' means 'but', 'perro' means 'dog'. Big difference!",
    severity: "critical",
  },
  {
    id: "3", type: "vocabulary",
    whatYouSaid: "Estoy caliente",
    correction: "Tengo calor",
    explanation: "'Estoy caliente' means 'I'm turned on' (sexual). 'Tengo calor' means 'I'm hot' (temperature). Classic mistake!",
    severity: "critical",
  },
  {
    id: "4", type: "fluency",
    whatYouSaid: "Um... eh... yo quiero... um... ir a...",
    correction: "Quiero ir a la tienda",
    explanation: "Try to reduce filler words. If you need time, use 'A ver...' or 'Bueno...' — they sound more natural in Spanish.",
    severity: "minor",
  },
  {
    id: "5", type: "grammar",
    whatYouSaid: "Ayer yo como pizza",
    correction: "Ayer yo comí pizza",
    explanation: "'Ayer' (yesterday) requires past tense. 'Comer' → 'comí' (I ate). Present tense 'como' means you're eating right now.",
    severity: "moderate",
  },
];

const VOCAB_LEARNED: VocabLearned[] = [
  { id: "1", word: "dar una mano", translation: "to give a hand / help", pronunciation: "/dar una ˈmano/", context: "¿Me puedes dar una mano con esto?", saved: false },
  { id: "2", word: "vale", translation: "okay / alright (Spain)", pronunciation: "/ˈbale/", context: "Vale, nos vemos mañana.", saved: false },
  { id: "3", word: "echar de menos", translation: "to miss (someone)", pronunciation: "/eˈtʃar de ˈmenos/", context: "Te echo de menos mucho.", saved: false },
  { id: "4", word: "quedar", translation: "to meet up / arrange", pronunciation: "/keˈðar/", context: "¿Quedamos a las ocho?", saved: false },
  { id: "5", word: "mola", translation: "cool / awesome (Spain slang)", pronunciation: "/ˈmola/", context: "¡Eso mola mucho!", saved: false },
  { id: "6", word: "flipar", translation: "to be amazed / shocked", pronunciation: "/fliˈpar/", context: "¡Estoy flipando!", saved: false },
];

const RECOMMENDATIONS: PracticeRecommendation[] = [
  { id: "1", title: "Rolled RR Drill", description: "Your biggest pronunciation gap. 10 minutes of targeted practice.", type: "pronunciation", duration: "10 min", priority: "high", icon: "mic", route: "/pronunciation-drill" },
  { id: "2", title: "Past Tense Conjugation", description: "Practice preterite tense with common verbs.", type: "grammar", duration: "15 min", priority: "high", icon: "create", route: "/grammar-practice" },
  { id: "3", title: "Speed Response Training", description: "Reduce your response time from 3.2s to under 2s.", type: "fluency", duration: "8 min", priority: "medium", icon: "flash", route: "/conversation-sim" },
  { id: "4", title: "Idiom Flashcards", description: "Learn 10 common Spanish idioms you missed today.", type: "vocabulary", duration: "5 min", priority: "medium", icon: "book", route: "/flashcard-review" },
];

const HIGHLIGHTS: ConversationHighlight[] = [
  { timestamp: "0:45", type: "great", text: "Perfect use of subjunctive mood!", note: "You said 'Espero que vengas' naturally without hesitation." },
  { timestamp: "2:12", type: "struggle", text: "Long pause on past tense", note: "5.8 second pause trying to conjugate 'ir' in preterite." },
  { timestamp: "4:30", type: "breakthrough", text: "First time using 'echar de menos' correctly!", note: "You heard it, understood it, and used it back — that's real acquisition!" },
  { timestamp: "7:15", type: "great", text: "Self-corrected 'soy tengo' to 'tengo'", note: "Catching your own mistakes is a sign of real progress." },
  { timestamp: "9:40", type: "struggle", text: "Confused 'por' and 'para'", note: "Used 'por' when 'para' was needed for purpose/destination." },
];

const SESSION_STATS = {
  duration: "12:34",
  wordsSpoken: 187,
  uniqueWords: 52,
  newWords: 6,
  mistakeCount: 5,
  selfCorrections: 3,
  responseTime: "3.2s avg",
  fillerWords: 4,
  overallScore: 76,
  previousOverall: 71,
  streakDays: 14,
  totalSessions: 47,
  language: "Spanish",
  topic: "Meeting Your Host Family",
  teacher: "Profesora Elena",
  date: "May 27, 2026",
};

// ─── COMPONENT ──────────────────────────────────────────────────────────────

export default function FeedbackReportScreen() {
  const colors = useColors();
  const [activeTab, setActiveTab] = useState<"overview" | "mistakes" | "vocab" | "practice">("overview");
  const [vocabList, setVocabList] = useState(VOCAB_LEARNED);
  const [expandedMistake, setExpandedMistake] = useState<string | null>(null);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const slideAnim = useRef(new Animated.Value(30)).current;

  useEffect(() => {
    Animated.parallel([
      Animated.timing(fadeAnim, { toValue: 1, duration: 600, useNativeDriver: true }),
      Animated.timing(slideAnim, { toValue: 0, duration: 600, useNativeDriver: true }),
    ]).start();
  }, []);

  const toggleSaveVocab = (id: string) => {
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setVocabList((prev) => prev.map((v) => v.id === id ? { ...v, saved: !v.saved } : v));
  };

  const getScoreColor = (score: number) => {
    if (score >= 85) return "#10B981";
    if (score >= 70) return "#3B82F6";
    if (score >= 55) return "#F59E0B";
    return "#EF4444";
  };

  const getSeverityColor = (severity: string) => {
    if (severity === "critical") return "#EF4444";
    if (severity === "moderate") return "#F59E0B";
    return "#94A3B8";
  };

  const getHighlightColor = (type: string) => {
    if (type === "great") return "#10B981";
    if (type === "breakthrough") return "#8B5CF6";
    return "#F59E0B";
  };

  const renderRadarChart = () => {
    const size = SCREEN_WIDTH - 80;
    const center = size / 2;
    const radius = center - 40;
    const angleStep = (2 * Math.PI) / SKILL_SCORES.length;

    return (
      <View style={[styles.radarContainer, { backgroundColor: colors.surface }]}>
        <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Skill Radar</Text>
        <View style={{ width: size, height: size, alignSelf: "center" }}>
          {/* Background rings */}
          {[0.25, 0.5, 0.75, 1].map((ring, i) => (
            <View key={i} style={{
              position: "absolute",
              width: radius * 2 * ring,
              height: radius * 2 * ring,
              borderRadius: radius * ring,
              borderWidth: 1,
              borderColor: colors.border,
              left: center - radius * ring,
              top: center - radius * ring,
              opacity: 0.4,
            }} />
          ))}
          {/* Score points and labels */}
          {SKILL_SCORES.map((skill, i) => {
            const angle = angleStep * i - Math.PI / 2;
            const scoreRadius = (skill.score / 100) * radius;
            const x = center + scoreRadius * Math.cos(angle);
            const y = center + scoreRadius * Math.sin(angle);
            const labelX = center + (radius + 25) * Math.cos(angle);
            const labelY = center + (radius + 25) * Math.sin(angle);

            return (
              <React.Fragment key={skill.id}>
                {/* Line from center */}
                <View style={{
                  position: "absolute",
                  left: center,
                  top: center,
                  width: 1,
                  height: scoreRadius,
                  backgroundColor: skill.color,
                  opacity: 0.3,
                  transform: [{ rotate: `${angle + Math.PI / 2}rad` }],
                  transformOrigin: "top",
                }} />
                {/* Score dot */}
                <View style={{
                  position: "absolute",
                  left: x - 8,
                  top: y - 8,
                  width: 16,
                  height: 16,
                  borderRadius: 8,
                  backgroundColor: skill.color,
                  justifyContent: "center",
                  alignItems: "center",
                }} />
                {/* Label */}
                <Text style={{
                  position: "absolute",
                  left: labelX - 30,
                  top: labelY - 8,
                  width: 60,
                  fontSize: 10,
                  color: colors.muted,
                  textAlign: "center",
                  fontWeight: "600",
                }}>{skill.name}</Text>
              </React.Fragment>
            );
          })}
        </View>
        {/* Score legend */}
        <View style={styles.legendRow}>
          {SKILL_SCORES.map((skill) => (
            <View key={skill.id} style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: skill.color }]} />
              <Text style={[styles.legendScore, { color: colors.foreground }]}>{skill.score}</Text>
              <Text style={[styles.legendChange, {
                color: skill.score > skill.previousScore ? "#10B981" : "#EF4444"
              }]}>
                {skill.score > skill.previousScore ? "+" : ""}{skill.score - skill.previousScore}
              </Text>
            </View>
          ))}
        </View>
      </View>
    );
  };

  const renderOverview = () => (
    <View>
      {/* Overall Score Hero */}
      <Animated.View style={[styles.heroCard, { backgroundColor: colors.surface, opacity: fadeAnim, transform: [{ translateY: slideAnim }] }]}>
        <View style={styles.heroTop}>
          <View style={[styles.scoreCircle, { borderColor: getScoreColor(SESSION_STATS.overallScore) }]}>
            <Text style={[styles.scoreNumber, { color: colors.foreground }]}>{SESSION_STATS.overallScore}</Text>
            <Text style={[styles.scoreLabel, { color: colors.muted }]}>/ 100</Text>
          </View>
          <View style={styles.heroInfo}>
            <Text style={[styles.heroTopic, { color: colors.foreground }]}>{SESSION_STATS.topic}</Text>
            <Text style={[styles.heroTeacher, { color: colors.muted }]}>with {SESSION_STATS.teacher}</Text>
            <Text style={[styles.heroDate, { color: colors.muted }]}>{SESSION_STATS.date} • {SESSION_STATS.duration}</Text>
            <View style={styles.changeRow}>
              <Ionicons name="trending-up" size={14} color="#10B981" />
              <Text style={{ color: "#10B981", fontSize: 12, marginLeft: 4, fontWeight: "600" }}>
                +{SESSION_STATS.overallScore - SESSION_STATS.previousOverall} from last session
              </Text>
            </View>
          </View>
        </View>

        {/* Quick Stats */}
        <View style={styles.quickStats}>
          <View style={styles.statItem}>
            <Text style={[styles.statValue, { color: colors.foreground }]}>{SESSION_STATS.wordsSpoken}</Text>
            <Text style={[styles.statLabel, { color: colors.muted }]}>Words</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={[styles.statValue, { color: colors.foreground }]}>{SESSION_STATS.newWords}</Text>
            <Text style={[styles.statLabel, { color: colors.muted }]}>New Words</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={[styles.statValue, { color: colors.foreground }]}>{SESSION_STATS.responseTime}</Text>
            <Text style={[styles.statLabel, { color: colors.muted }]}>Resp. Time</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={[styles.statValue, { color: colors.foreground }]}>{SESSION_STATS.selfCorrections}</Text>
            <Text style={[styles.statLabel, { color: colors.muted }]}>Self-Fixes</Text>
          </View>
        </View>
      </Animated.View>

      {/* Radar Chart */}
      {renderRadarChart()}

      {/* Conversation Timeline */}
      <View style={[styles.timelineCard, { backgroundColor: colors.surface }]}>
        <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Session Highlights</Text>
        {HIGHLIGHTS.map((h, i) => (
          <View key={i} style={styles.timelineItem}>
            <View style={[styles.timelineDot, { backgroundColor: getHighlightColor(h.type) }]} />
            <View style={styles.timelineContent}>
              <View style={styles.timelineHeader}>
                <Text style={[styles.timelineTimestamp, { color: colors.muted }]}>{h.timestamp}</Text>
                <View style={[styles.typeBadge, { backgroundColor: getHighlightColor(h.type) + "20" }]}>
                  <Text style={[styles.typeBadgeText, { color: getHighlightColor(h.type) }]}>
                    {h.type === "great" ? "✓ Great" : h.type === "breakthrough" ? "⚡ Breakthrough" : "⚠ Struggle"}
                  </Text>
                </View>
              </View>
              <Text style={[styles.timelineText, { color: colors.foreground }]}>{h.text}</Text>
              <Text style={[styles.timelineNote, { color: colors.muted }]}>{h.note}</Text>
            </View>
          </View>
        ))}
      </View>

      {/* Personal Teacher Note */}
      <View style={[styles.timelineCard, { backgroundColor: colors.surface, borderLeftWidth: 3, borderLeftColor: '#8B5CF6' }]}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <View style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: '#8B5CF6' + '20', alignItems: 'center', justifyContent: 'center' }}>
            <Ionicons name="chatbubble-ellipses" size={16} color="#8B5CF6" />
          </View>
          <Text style={{ fontSize: 14, fontWeight: '700', color: colors.foreground }}>A Note From Your Teacher</Text>
        </View>
        <Text style={{ fontSize: 14, color: colors.foreground, lineHeight: 22, fontStyle: 'italic' }}>
          {"I noticed you nailed the subjunctive today — that's been a tough one for you, and you used it without even thinking. That's real progress. "}
          {"The 'por' vs 'para' confusion is totally normal at this stage. Here's a trick: if you can replace it with 'in order to', use 'para'. "}
          {"Tomorrow, let's do a quick 5-minute drill on that. You're closer than you think."}
        </Text>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12, paddingTop: 12, borderTopWidth: 0.5, borderTopColor: 'rgba(148,163,184,0.2)' }}>
          <Ionicons name="heart" size={14} color="#EF4444" />
          <Text style={{ fontSize: 12, color: colors.muted }}>Written just for you based on today's session</Text>
        </View>
      </View>
    </View>
  );

  const renderMistakes = () => (
    <View>
      <View style={[styles.mistakeHeader, { backgroundColor: colors.surface }]}>
        <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Mistakes Breakdown</Text>
        <Text style={[styles.mistakeCount, { color: colors.muted }]}>{MISTAKES.length} corrections</Text>
      </View>
      {MISTAKES.map((mistake) => (
        <TouchableOpacity
          key={mistake.id}
          style={[styles.mistakeCard, { backgroundColor: colors.surface }]}
          onPress={() => {
            if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
            setExpandedMistake(expandedMistake === mistake.id ? null : mistake.id);
          }}
          activeOpacity={0.7}
        >
          <View style={styles.mistakeTop}>
            <View style={[styles.severityDot, { backgroundColor: getSeverityColor(mistake.severity) }]} />
            <View style={styles.mistakeTypeChip}>
              <Text style={styles.mistakeTypeText}>{mistake.type}</Text>
            </View>
            <View style={[styles.severityBadge, { backgroundColor: getSeverityColor(mistake.severity) + "20" }]}>
              <Text style={[styles.severityText, { color: getSeverityColor(mistake.severity) }]}>{mistake.severity}</Text>
            </View>
          </View>
          <View style={styles.mistakeComparison}>
            <View style={styles.mistakeWrong}>
              <Ionicons name="close-circle" size={14} color="#EF4444" />
              <Text style={[styles.mistakeWrongText, { color: "#EF4444" }]}>{mistake.whatYouSaid}</Text>
            </View>
            <View style={styles.mistakeCorrect}>
              <Ionicons name="checkmark-circle" size={14} color="#10B981" />
              <Text style={[styles.mistakeCorrectText, { color: "#10B981" }]}>{mistake.correction}</Text>
            </View>
          </View>
          {expandedMistake === mistake.id && (
            <View style={[styles.mistakeExplanation, { borderTopColor: colors.border }]}>
              <Ionicons name="bulb" size={16} color="#F59E0B" />
              <Text style={[styles.explanationText, { color: colors.foreground }]}>{mistake.explanation}</Text>
            </View>
          )}
        </TouchableOpacity>
      ))}
    </View>
  );

  const renderVocab = () => (
    <View>
      <View style={[styles.vocabHeader, { backgroundColor: colors.surface }]}>
        <Text style={[styles.sectionTitle, { color: colors.foreground }]}>New Vocabulary</Text>
        <Text style={[styles.vocabCount, { color: colors.muted }]}>{vocabList.length} words learned</Text>
      </View>
      {vocabList.map((vocab) => (
        <View key={vocab.id} style={[styles.vocabCard, { backgroundColor: colors.surface }]}>
          <View style={styles.vocabTop}>
            <View>
              <Text style={[styles.vocabWord, { color: colors.foreground }]}>{vocab.word}</Text>
              <Text style={[styles.vocabPronunciation, { color: colors.muted }]}>{vocab.pronunciation}</Text>
            </View>
            <TouchableOpacity
              onPress={() => toggleSaveVocab(vocab.id)}
              style={[styles.saveBtn, vocab.saved && styles.saveBtnActive]}
            >
              <Ionicons
                name={vocab.saved ? "bookmark" : "bookmark-outline"}
                size={20}
                color={vocab.saved ? "#3B82F6" : colors.muted}
              />
            </TouchableOpacity>
          </View>
          <Text style={[styles.vocabTranslation, { color: colors.foreground }]}>{vocab.translation}</Text>
          <View style={[styles.vocabContext, { backgroundColor: colors.background }]}>
            <Ionicons name="chatbubble-outline" size={12} color={colors.muted} />
            <Text style={[styles.vocabContextText, { color: colors.muted }]}>{vocab.context}</Text>
          </View>
        </View>
      ))}
      <TouchableOpacity style={[styles.saveAllBtn, { backgroundColor: "#3B82F6" }]}>
        <Ionicons name="bookmark" size={18} color="#FFF" />
        <Text style={styles.saveAllText}>Save All to Flashcards</Text>
      </TouchableOpacity>
    </View>
  );

  const renderPractice = () => (
    <View>
      <View style={[styles.practiceHeader, { backgroundColor: colors.surface }]}>
        <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Recommended Practice</Text>
        <Text style={[styles.practiceSubtitle, { color: colors.muted }]}>Based on today's weak areas</Text>
      </View>
      {RECOMMENDATIONS.map((rec) => (
        <TouchableOpacity
          key={rec.id}
          style={[styles.practiceCard, { backgroundColor: colors.surface }]}
          onPress={() => {
            if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
            router.push(rec.route as any);
          }}
          activeOpacity={0.7}
        >
          <View style={styles.practiceLeft}>
            <View style={[styles.practiceIcon, {
              backgroundColor: rec.priority === "high" ? "#EF444420" : rec.priority === "medium" ? "#F59E0B20" : "#10B98120"
            }]}>
              <Ionicons name={rec.icon as any} size={20} color={
                rec.priority === "high" ? "#EF4444" : rec.priority === "medium" ? "#F59E0B" : "#10B981"
              } />
            </View>
            <View style={styles.practiceInfo}>
              <Text style={[styles.practiceTitle, { color: colors.foreground }]}>{rec.title}</Text>
              <Text style={[styles.practiceDesc, { color: colors.muted }]}>{rec.description}</Text>
              <View style={styles.practiceMeta}>
                <Ionicons name="time-outline" size={12} color={colors.muted} />
                <Text style={[styles.practiceDuration, { color: colors.muted }]}>{rec.duration}</Text>
                <View style={[styles.priorityChip, {
                  backgroundColor: rec.priority === "high" ? "#EF444420" : rec.priority === "medium" ? "#F59E0B20" : "#10B98120"
                }]}>
                  <Text style={[styles.priorityText, {
                    color: rec.priority === "high" ? "#EF4444" : rec.priority === "medium" ? "#F59E0B" : "#10B981"
                  }]}>{rec.priority}</Text>
                </View>
              </View>
            </View>
          </View>
          <Ionicons name="chevron-forward" size={18} color={colors.muted} />
        </TouchableOpacity>
      ))}
    </View>
  );

  const tabs = [
    { id: "overview" as const, label: "Overview", icon: "stats-chart" },
    { id: "mistakes" as const, label: "Mistakes", icon: "alert-circle" },
    { id: "vocab" as const, label: "Vocab", icon: "book" },
    { id: "practice" as const, label: "Practice", icon: "fitness" },
  ];

  return (
    <ScreenContainer edges={["top", "left", "right"]}>
      {/* Header */}
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={22} color={colors.foreground} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.foreground }]}>Session Report</Text>
        <TouchableOpacity style={styles.shareBtn}>
          <Ionicons name="share-outline" size={20} color={colors.primary} />
        </TouchableOpacity>
      </View>

      {/* Tab Bar */}
      <View style={[styles.tabBar, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}>
        {tabs.map((tab) => (
          <TouchableOpacity
            key={tab.id}
            style={[styles.tab, activeTab === tab.id && { borderBottomColor: colors.primary }]}
            onPress={() => {
              if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
              setActiveTab(tab.id);
            }}
          >
            <Ionicons
              name={tab.icon as any}
              size={16}
              color={activeTab === tab.id ? colors.primary : colors.muted}
            />
            <Text style={[styles.tabText, { color: activeTab === tab.id ? colors.primary : colors.muted }]}>
              {tab.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Content */}
      <ScrollView style={styles.scrollContent} contentContainerStyle={styles.scrollContainer} showsVerticalScrollIndicator={false}>
        {activeTab === "overview" && renderOverview()}
        {activeTab === "mistakes" && renderMistakes()}
        {activeTab === "vocab" && renderVocab()}
        {activeTab === "practice" && renderPractice()}
      </ScrollView>
    </ScreenContainer>
  );
}

// ─── STYLES ─────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 0.5 },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 17, fontWeight: "700" },
  shareBtn: { padding: 4 },
  tabBar: { flexDirection: "row", paddingHorizontal: 8, borderBottomWidth: 0.5 },
  tab: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 12, gap: 4, borderBottomWidth: 2, borderBottomColor: "transparent" },
  tabText: { fontSize: 12, fontWeight: "600" },
  scrollContent: { flex: 1 },
  scrollContainer: { paddingBottom: 100 },
  heroCard: { margin: 16, borderRadius: 16, padding: 20 },
  heroTop: { flexDirection: "row", alignItems: "center", gap: 16 },
  scoreCircle: { width: 80, height: 80, borderRadius: 40, borderWidth: 4, justifyContent: "center", alignItems: "center" },
  scoreNumber: { fontSize: 28, fontWeight: "800" },
  scoreLabel: { fontSize: 11 },
  heroInfo: { flex: 1 },
  heroTopic: { fontSize: 16, fontWeight: "700" },
  heroTeacher: { fontSize: 13, marginTop: 2 },
  heroDate: { fontSize: 12, marginTop: 2 },
  changeRow: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  quickStats: { flexDirection: "row", justifyContent: "space-between", marginTop: 20, paddingTop: 16, borderTopWidth: 0.5, borderTopColor: "rgba(148,163,184,0.2)" },
  statItem: { alignItems: "center" },
  statValue: { fontSize: 18, fontWeight: "700" },
  statLabel: { fontSize: 10, marginTop: 2 },
  radarContainer: { margin: 16, borderRadius: 16, padding: 20 },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 16 },
  legendRow: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 12, marginTop: 16 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendScore: { fontSize: 12, fontWeight: "700" },
  legendChange: { fontSize: 10, fontWeight: "600" },
  timelineCard: { margin: 16, borderRadius: 16, padding: 20 },
  timelineItem: { flexDirection: "row", marginBottom: 16, gap: 12 },
  timelineDot: { width: 10, height: 10, borderRadius: 5, marginTop: 4 },
  timelineContent: { flex: 1 },
  timelineHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  timelineTimestamp: { fontSize: 11, fontWeight: "600" },
  typeBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  typeBadgeText: { fontSize: 10, fontWeight: "600" },
  timelineText: { fontSize: 14, fontWeight: "600" },
  timelineNote: { fontSize: 12, marginTop: 2 },
  mistakeHeader: { margin: 16, marginBottom: 8, borderRadius: 16, padding: 20 },
  mistakeCount: { fontSize: 12 },
  mistakeCard: { marginHorizontal: 16, marginBottom: 10, borderRadius: 12, padding: 16 },
  mistakeTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  severityDot: { width: 8, height: 8, borderRadius: 4 },
  mistakeTypeChip: { backgroundColor: "rgba(59,130,246,0.15)", paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  mistakeTypeText: { fontSize: 10, fontWeight: "600", color: "#3B82F6", textTransform: "capitalize" },
  severityBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  severityText: { fontSize: 10, fontWeight: "600", textTransform: "capitalize" },
  mistakeComparison: { gap: 6 },
  mistakeWrong: { flexDirection: "row", alignItems: "center", gap: 6 },
  mistakeWrongText: { fontSize: 13, textDecorationLine: "line-through" },
  mistakeCorrect: { flexDirection: "row", alignItems: "center", gap: 6 },
  mistakeCorrectText: { fontSize: 13, fontWeight: "600" },
  mistakeExplanation: { marginTop: 12, paddingTop: 12, borderTopWidth: 0.5, flexDirection: "row", gap: 8, alignItems: "flex-start" },
  explanationText: { flex: 1, fontSize: 13, lineHeight: 18 },
  vocabHeader: { margin: 16, marginBottom: 8, borderRadius: 16, padding: 20 },
  vocabCount: { fontSize: 12 },
  vocabCard: { marginHorizontal: 16, marginBottom: 10, borderRadius: 12, padding: 16 },
  vocabTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  vocabWord: { fontSize: 16, fontWeight: "700" },
  vocabPronunciation: { fontSize: 12, marginTop: 2 },
  vocabTranslation: { fontSize: 14, marginTop: 8 },
  vocabContext: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 10, padding: 10, borderRadius: 8 },
  vocabContextText: { fontSize: 12, flex: 1, fontStyle: "italic" },
  saveBtn: { padding: 8 },
  saveBtnActive: {},
  saveAllBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginHorizontal: 16, marginTop: 8, padding: 14, borderRadius: 12 },
  saveAllText: { color: "#FFF", fontSize: 14, fontWeight: "700" },
  practiceHeader: { margin: 16, marginBottom: 8, borderRadius: 16, padding: 20 },
  practiceSubtitle: { fontSize: 12 },
  practiceCard: { flexDirection: "row", alignItems: "center", marginHorizontal: 16, marginBottom: 10, borderRadius: 12, padding: 16 },
  practiceLeft: { flex: 1, flexDirection: "row", gap: 12, alignItems: "center" },
  practiceIcon: { width: 44, height: 44, borderRadius: 12, justifyContent: "center", alignItems: "center" },
  practiceInfo: { flex: 1 },
  practiceTitle: { fontSize: 14, fontWeight: "700" },
  practiceDesc: { fontSize: 12, marginTop: 2 },
  practiceMeta: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 6 },
  practiceDuration: { fontSize: 11, marginRight: 8 },
  priorityChip: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: 4 },
  priorityText: { fontSize: 9, fontWeight: "700", textTransform: "uppercase" },
});
