/**
 * Smart Practice Screen
 * 
 * The system-generated practice hub. Shows:
 * - Active homework assignments (auto-generated by the intelligence engine)
 * - Practice recommendations based on struggle detection
 * - Quick drills for weak areas
 * 
 * This is where the "smart system" surfaces personalized exercises.
 */
import { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  Pressable,
  ScrollView,
  StyleSheet,
  ActivityIndicator,
  Platform,
} from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import * as Haptics from "expo-haptics";
import {
  getActiveHomework,
  getActiveRecommendations,
  getActiveInsights,
  getStudentProfile,
  getStruggles,
  startRecommendation,
  dismissRecommendation,
  completeHomeworkExercise,
  dismissInsight,
  type HomeworkAssignment,
  type PracticeRecommendation,
  type IntelligenceInsight,
  type StudentProfile,
  type StruggleArea,
} from "@/lib/learning-intelligence";
import {
  getDueCards,
  getUpcomingCards,
  getStats,
  getNextStudyRecommendation,
  reviewCard,
  type SRSCard,
  type SimpleQuality,
} from "@/lib/spaced-repetition";
import { trpc } from "@/lib/trpc";
import {
  getGamificationState,
  recordCardReview,
  completeReviewSession,
  getLevelProgress,
  getStreakInfo,
  type SRSGamificationState,
  type ReviewResult,
} from "@/lib/srs-gamification";
import { markTodayAsPracticed } from "@/lib/streak-notifications";
import { markPracticeAndToast } from "@/lib/streak-practice-helper";
import { useUsage } from "@/lib/usage-context";


export default function SmartPracticeScreen() {
  const { showStreakToast } = useUsage();
  const router = useRouter();
  const params = useLocalSearchParams<{ homeworkId?: string; recommendationId?: string }>();
  
  const [homework, setHomework] = useState<HomeworkAssignment[]>([]);
  const [recommendations, setRecommendations] = useState<PracticeRecommendation[]>([]);
  const [insights, setInsights] = useState<IntelligenceInsight[]>([]);
  const [profile, setProfile] = useState<StudentProfile | null>(null);
  const [struggles, setStruggles] = useState<StruggleArea[]>([]);
  const [loading, setLoading] = useState(true);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);
  const [analyzingAI, setAnalyzingAI] = useState(false);

  // Spaced Repetition State
  const [dueCards, setDueCards] = useState<SRSCard[]>([]);
  const [upcomingCards, setUpcomingCards] = useState<SRSCard[]>([]);
  const [srsStats, setSrsStats] = useState<{ totalCards: number; dueToday: number; reviewedToday: number; averageRetention: number; matureCards: number; youngCards: number; newCards: number } | null>(null);
  const [studyRec, setStudyRec] = useState<{ hasDueCards: boolean; dueCount: number; nextDueIn: string; urgency: string; message: string } | null>(null);
  const [reviewingCard, setReviewingCard] = useState<SRSCard | null>(null);

  // Gamification State
  const [gamification, setGamification] = useState<SRSGamificationState | null>(null);
  const [lastReviewResult, setLastReviewResult] = useState<ReviewResult | null>(null);
  const [showXPPopup, setShowXPPopup] = useState(false);

  const analyzeProgressMutation = trpc.learningIntelligence.analyzeStudentProgress.useMutation();

  const loadData = useCallback(async () => {
    try {
      const [hw, recs, ins, prof, strug, due, upcoming, stats, rec] = await Promise.all([
        getActiveHomework(),
        getActiveRecommendations(),
        getActiveInsights(),
        getStudentProfile(),
        getStruggles(),
        getDueCards(),
        getUpcomingCards(7),
        getStats(),
        getNextStudyRecommendation(),
      ]);
      setHomework(hw);
      setRecommendations(recs);
      setInsights(ins);
      setProfile(prof);
      setStruggles(strug);
      setDueCards(due);
      setUpcomingCards(upcoming);
      setSrsStats(stats);
      setStudyRec(rec);
      // Load gamification state
      const gamState = await getGamificationState();
      setGamification(gamState);
    } catch (err) {
      console.warn("Failed to load intelligence data:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, []);

  // Request AI analysis when struggles exist
  const requestAIAnalysis = async () => {
    if (struggles.length === 0) return;
    setAnalyzingAI(true);
    try {
      const result = await analyzeProgressMutation.mutateAsync({
        struggles: struggles.map((s) => ({
          category: s.category,
          topic: s.topic,
          exerciseType: s.exerciseType,
          language: s.language,
          severity: s.severity,
          accuracy: s.accuracy,
          attempts: s.attempts,
          trend: s.trend,
        })),
        overallAccuracy: profile?.overallAccuracy || 0,
        totalExercises: profile?.totalExercisesCompleted || 0,
        language: struggles[0]?.language || "Spanish",
        level: "A2",
      });
      if (result.success && result.analysis) {
        setAiAnalysis(result.analysis);
      }
    } catch (err) {
      console.warn("AI analysis failed:", err);
    } finally {
      setAnalyzingAI(false);
    }
  };

  const handleStartRecommendation = async (rec: PracticeRecommendation) => {
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    await startRecommendation(rec.id);
    // Navigate to adaptive lesson with the recommendation config
    router.push({
      pathname: "/adaptive-lesson" as any,
      params: {
        language: rec.exerciseConfig.language,
        level: rec.exerciseConfig.level,
        topic: rec.exerciseConfig.topic,
        category: rec.exerciseConfig.focusAreas[0] || "general",
        source: "smart_practice",
        recommendationId: rec.id,
      },
    });
  };

  const handleStartHomeworkExercise = async (hw: HomeworkAssignment, exerciseIndex: number) => {
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const exercise = hw.exercises[exerciseIndex];
    if (!exercise || exercise.status === "completed") return;
    
    router.push({
      pathname: "/adaptive-lesson" as any,
      params: {
        language: exercise.config.language,
        level: exercise.config.level,
        topic: exercise.config.topic,
        category: exercise.config.focusAreas?.[0] || "general",
        source: "homework",
        homeworkId: hw.id,
        exerciseId: exercise.id,
      },
    });
  };

  const handleDismissRecommendation = async (rec: PracticeRecommendation) => {
    await dismissRecommendation(rec.id);
    setRecommendations((prev) => prev.filter((r) => r.id !== rec.id));
  };

  const handleDismissInsight = async (index: number) => {
    await dismissInsight(index);
    setInsights((prev) => prev.filter((_, i) => i !== index));
  };

  if (loading) {
    return (
      <ScreenContainer className="p-6">
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#00AAFF" />
          <Text style={styles.loadingText}>Loading your practice plan...</Text>
        </View>
      </ScreenContainer>
    );
  }

  // Handle SRS card review
  const handleReviewCard = async (card: SRSCard, quality: SimpleQuality) => {
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    await reviewCard(card.id, quality);
    
    // Record gamification XP
    const isCorrect = quality !== "forgot";
    const isFirstTry = quality === "easy" || quality === "good";
    const result = await recordCardReview({
      correct: isCorrect,
      firstTry: isFirstTry,
      onTime: true, // Card was due today
    });
    setLastReviewResult(result);
    setShowXPPopup(true);
    setTimeout(() => setShowXPPopup(false), 2500);
    
    // Haptic feedback for level up or badge
    if (result.levelUp) {
      if (Platform.OS !== "web") Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    }
    
    setReviewingCard(null);
    // Refresh due cards and gamification
    const [newDue, newStats, gamState] = await Promise.all([
      getDueCards(),
      getStats(),
      getGamificationState(),
    ]);
    setDueCards(newDue);
    setSrsStats(newStats);
    setGamification(gamState);
    
    // Check if session complete (no more due cards)
    if (newDue.length === 0) {
      const sessionResult = await completeReviewSession();
      markPracticeAndToast(showStreakToast);
      if (sessionResult) {
        setLastReviewResult(sessionResult);
        setShowXPPopup(true);
        setTimeout(() => setShowXPPopup(false), 3000);
      }
    }
  };

  const handleStartSRSReview = (card: SRSCard) => {
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    // Navigate to adaptive lesson with the card's exercise config
    router.push({
      pathname: "/adaptive-lesson" as any,
      params: {
        language: card.language,
        level: card.difficulty === "beginner" ? "A1" : card.difficulty === "intermediate" ? "B1" : "C1",
        topic: card.topic,
        category: card.subtopic || "general",
        source: "srs_review",
        srsCardId: card.id,
      },
    });
  };

  const hasContent = homework.length > 0 || recommendations.length > 0 || insights.length > 0 || struggles.length > 0 || dueCards.length > 0;

  return (
    <ScreenContainer>
      <ScrollView contentContainerStyle={{ paddingBottom: 40 }}>
        {/* Header */}
        <View style={styles.header}>
          <Pressable onPress={() => router.back()} style={({ pressed }) => [pressed && { opacity: 0.6 }]}>
            <Text style={styles.backBtn}>← Back</Text>
          </Pressable>
          <Text style={styles.title}>Smart Practice</Text>
          <Text style={styles.subtitle}>
            {hasContent ? "Personalized exercises based on your performance" : "Complete some lessons to get personalized recommendations"}
          </Text>
        </View>

        {/* Gamification Stats Bar */}
        {gamification && (
          <View style={styles.gamBar}>
            <View style={styles.gamRow}>
              <View style={styles.gamStat}>
                <Text style={styles.gamIcon}>🔥</Text>
                <Text style={styles.gamValue}>{gamification.currentStreak}</Text>
                <Text style={styles.gamLabel}>Streak</Text>
              </View>
              <View style={styles.gamStat}>
                <Text style={styles.gamIcon}>⭐</Text>
                <Text style={styles.gamValue}>Lv.{gamification.level}</Text>
                <Text style={styles.gamLabel}>{gamification.totalXP} XP</Text>
              </View>
              <View style={styles.gamStat}>
                <Text style={styles.gamIcon}>🎯</Text>
                <Text style={styles.gamValue}>{gamification.todayXP}</Text>
                <Text style={styles.gamLabel}>Today</Text>
              </View>
              <View style={styles.gamStat}>
                <Text style={styles.gamIcon}>🏆</Text>
                <Text style={styles.gamValue}>{gamification.badges.length}</Text>
                <Text style={styles.gamLabel}>Badges</Text>
              </View>
            </View>
            {/* XP Progress Bar */}
            <View style={styles.xpBarContainer}>
              <View style={styles.xpBarBg}>
                <View style={[styles.xpBarFill, { width: `${Math.min(((gamification.totalXP % 1000) / (gamification.xpToNextLevel + (gamification.totalXP % 1000))) * 100, 100)}%` as any }]} />
              </View>
              <Text style={styles.xpBarText}>{gamification.xpToNextLevel} XP to Level {gamification.level + 1}</Text>
            </View>
            {gamification.perfectRecallToday && gamification.cardsReviewedToday >= 5 && (
              <View style={styles.perfectBadge}>
                <Text style={styles.perfectBadgeText}>🎯 Perfect Recall Today!</Text>
              </View>
            )}
          </View>
        )}

        {/* XP Popup */}
        {showXPPopup && lastReviewResult && (
          <View style={styles.xpPopup}>
            <Text style={styles.xpPopupText}>{lastReviewResult.message}</Text>
            {lastReviewResult.newBadges.length > 0 && (
              <Text style={styles.xpPopupBadge}>
                {lastReviewResult.newBadges.map(b => `${b.icon} ${b.name}`).join(" ")}
              </Text>
            )}
          </View>
        )}

        {/* Spaced Repetition - Due Reviews */}
        {dueCards.length > 0 && (
          <View style={styles.section}>
            <View style={styles.srsHeader}>
              <Text style={styles.sectionTitle}>🧠 Due for Review</Text>
              {srsStats && (
                <View style={styles.srsStatsRow}>
                  <Text style={styles.srsStatText}>{srsStats.reviewedToday} done today</Text>
                  <Text style={styles.srsStatDivider}>•</Text>
                  <Text style={styles.srsStatText}>{srsStats.averageRetention}% retention</Text>
                </View>
              )}
            </View>
            <Text style={styles.sectionDesc}>
              These exercises are scheduled based on your forgetting curve — review them now for optimal retention
            </Text>
            {dueCards.slice(0, 5).map((card) => (
              <Pressable
                key={card.id}
                onPress={() => handleStartSRSReview(card)}
                style={({ pressed }) => [styles.srsCard, pressed && { opacity: 0.8 }]}
              >
                <View style={styles.srsCardLeft}>
                  <Text style={styles.srsCardTopic}>{card.topic}</Text>
                  {card.subtopic && <Text style={styles.srsCardSubtopic}>{card.subtopic}</Text>}
                  <View style={styles.srsCardMeta}>
                    <Text style={styles.srsCardType}>{card.exerciseType.replace(/_/g, " ")}</Text>
                    <Text style={styles.srsCardDot}>•</Text>
                    <Text style={styles.srsCardInterval}>
                      {card.repetitions === 0 ? "New" : `Interval: ${card.interval}d`}
                    </Text>
                    <Text style={styles.srsCardDot}>•</Text>
                    <Text style={styles.srsCardAccuracy}>
                      {card.totalReviews > 0 ? `${Math.round((card.correctReviews / card.totalReviews) * 100)}%` : "—"}
                    </Text>
                  </View>
                </View>
                <Text style={styles.srsCardArrow}>→</Text>
              </Pressable>
            ))}
            {dueCards.length > 5 && (
              <Text style={styles.srsMoreText}>+{dueCards.length - 5} more due</Text>
            )}
          </View>
        )}

        {/* Upcoming Reviews Preview */}
        {upcomingCards.length > 0 && dueCards.length === 0 && studyRec && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>📅 Upcoming Reviews</Text>
            <View style={styles.srsNextCard}>
              <Text style={styles.srsNextMessage}>{studyRec.message}</Text>
              <Text style={styles.srsNextCount}>{upcomingCards.length} cards scheduled this week</Text>
            </View>
          </View>
        )}

        {/* Intelligence Insights */}
        {insights.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>🧠 System Insights</Text>
            {insights.map((insight, i) => (
              <View key={i} style={[styles.insightCard, insight.type === "homework_assigned" && styles.insightCardUrgent]}>
                <View style={styles.insightHeader}>
                  <Text style={styles.insightTitle}>{insight.title}</Text>
                  <Pressable onPress={() => handleDismissInsight(i)} style={({ pressed }) => [pressed && { opacity: 0.6 }]}>
                    <Text style={styles.dismissBtn}>✕</Text>
                  </Pressable>
                </View>
                <Text style={styles.insightMessage}>{insight.message}</Text>
                {insight.actionLabel && (
                  <Pressable
                    onPress={() => {
                      if (insight.actionRoute) {
                        router.push(insight.actionRoute as any);
                      }
                    }}
                    style={({ pressed }) => [styles.insightAction, pressed && { opacity: 0.8 }]}
                  >
                    <Text style={styles.insightActionText}>{insight.actionLabel}</Text>
                  </Pressable>
                )}
              </View>
            ))}
          </View>
        )}

        {/* Active Homework */}
        {homework.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>📚 Homework</Text>
            <Text style={styles.sectionDesc}>Auto-generated practice targeting your weak areas</Text>
            {/* Legacy homework route redirect: "/homework" */}
            {homework.map((hw) => {
              const completedCount = hw.exercises.filter((e) => e.status === "completed").length;
              const progress = hw.exercises.length > 0 ? completedCount / hw.exercises.length : 0;
              const isOverdue = hw.dueAt < Date.now();
              return (
                <View key={hw.id} style={[styles.homeworkCard, isOverdue && styles.homeworkOverdue]}>
                  <View style={styles.homeworkHeader}>
                    <Text style={styles.homeworkTitle}>{hw.title}</Text>
                    <View style={[styles.badge, isOverdue ? styles.badgeRed : styles.badgeBlue]}>
                      <Text style={styles.badgeText}>
                        {isOverdue ? "Overdue" : `Due ${new Date(hw.dueAt).toLocaleDateString()}`}
                      </Text>
                    </View>
                  </View>
                  <Text style={styles.homeworkDesc}>{hw.description}</Text>
                  <Text style={styles.homeworkAssigner}>Assigned by: {hw.assignedBy === "system" ? "🧠 System Intelligence" : hw.assignedBy === "wave_cloud" ? "☁️ Wave Cloud" : "👩‍🏫 Teacher"}</Text>
                  
                  {/* Progress bar */}
                  <View style={styles.progressBarContainer}>
                    <View style={[styles.progressBar, { width: `${progress * 100}%` as any }]} />
                  </View>
                  <Text style={styles.progressText}>{completedCount}/{hw.exercises.length} exercises completed</Text>

                  {/* Exercise list */}
                  {hw.exercises.map((ex, i) => (
                    <Pressable
                      key={ex.id}
                      onPress={() => handleStartHomeworkExercise(hw, i)}
                      disabled={ex.status === "completed"}
                      style={({ pressed }) => [
                        styles.exerciseItem,
                        ex.status === "completed" && styles.exerciseCompleted,
                        pressed && { opacity: 0.8 },
                      ]}
                    >
                      <Text style={styles.exerciseIcon}>
                        {ex.status === "completed" ? "✅" : "⚪"}
                      </Text>
                      <View style={{ flex: 1 }}>
                        <Text style={[styles.exerciseTitle, ex.status === "completed" && styles.exerciseTitleDone]}>
                          {ex.title}
                        </Text>
                        <Text style={styles.exerciseType}>{ex.type.replace(/_/g, " ")}</Text>
                      </View>
                      {ex.accuracy !== undefined && (
                        <Text style={styles.exerciseAccuracy}>{ex.accuracy}%</Text>
                      )}
                      {ex.status !== "completed" && (
                        <Text style={styles.exerciseArrow}>→</Text>
                      )}
                    </Pressable>
                  ))}
                </View>
              );
            })}
          </View>
        )}

        {/* Practice Recommendations */}
        {recommendations.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>💡 Recommended Practice</Text>
            <Text style={styles.sectionDesc}>The system detected areas that need attention</Text>
            {recommendations.map((rec) => (
              <View key={rec.id} style={[styles.recCard, rec.urgency === "critical" && styles.recCardCritical]}>
                <View style={styles.recHeader}>
                  <View style={[styles.urgencyDot, styles[`urgency_${rec.urgency}` as keyof typeof styles] as any]} />
                  <Text style={styles.recTitle}>{rec.title}</Text>
                  <Text style={styles.recTime}>~{rec.estimatedMinutes}min</Text>
                </View>
                <Text style={styles.recDescription}>{rec.description}</Text>
                <Text style={styles.recReason}>{rec.reason}</Text>
                <View style={styles.recActions}>
                  <Pressable
                    onPress={() => handleStartRecommendation(rec)}
                    style={({ pressed }) => [styles.startBtn, pressed && { opacity: 0.8 }]}
                  >
                    <Text style={styles.startBtnText}>Start Practice</Text>
                  </Pressable>
                  <Pressable
                    onPress={() => handleDismissRecommendation(rec)}
                    style={({ pressed }) => [styles.skipBtn, pressed && { opacity: 0.6 }]}
                  >
                    <Text style={styles.skipBtnText}>Skip</Text>
                  </Pressable>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Struggle Areas Overview */}
        {struggles.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>🔍 Areas to Improve</Text>
            {struggles.map((s) => (
              <View key={s.id} style={styles.struggleItem}>
                <View style={styles.struggleHeader}>
                  <Text style={styles.struggleTopic}>{s.topic}</Text>
                  <View style={[styles.severityBadge, s.severity === "severe" ? styles.severityRed : s.severity === "moderate" ? styles.severityOrange : styles.severityYellow]}>
                    <Text style={styles.severityText}>{s.severity}</Text>
                  </View>
                </View>
                <View style={styles.struggleStats}>
                  <Text style={styles.struggleStat}>Accuracy: {s.accuracy}%</Text>
                  <Text style={styles.struggleStat}>Attempts: {s.attempts}</Text>
                  <Text style={[styles.struggleTrend, s.trend === "improving" ? styles.trendGreen : s.trend === "declining" ? styles.trendRed : styles.trendGray]}>
                    {s.trend === "improving" ? "↑" : s.trend === "declining" ? "↓" : "→"} {s.trend}
                  </Text>
                </View>
              </View>
            ))}

            {/* AI Analysis button */}
            {!aiAnalysis && (
              <Pressable
                onPress={requestAIAnalysis}
                disabled={analyzingAI}
                style={({ pressed }) => [styles.aiAnalysisBtn, pressed && { opacity: 0.8 }]}
              >
                {analyzingAI ? (
                  <ActivityIndicator size="small" color="#fff" />
                ) : (
                  <Text style={styles.aiAnalysisBtnText}>🤖 Get AI Analysis & Recommendations</Text>
                )}
              </Pressable>
            )}

            {/* AI Analysis Results */}
            {aiAnalysis && (
              <View style={styles.aiResultCard}>
                <Text style={styles.aiResultTitle}>🤖 AI Teacher Says:</Text>
                <Text style={styles.aiEncouragement}>{aiAnalysis.encouragement}</Text>
                {aiAnalysis.practiceItems?.map((item: any, i: number) => (
                  <View key={i} style={styles.aiPracticeItem}>
                    <Text style={styles.aiPracticeTitle}>{item.title}</Text>
                    <Text style={styles.aiPracticeDesc}>{item.description}</Text>
                  </View>
                ))}
                {aiAnalysis.teachingStrategy && (
                  <View style={styles.strategyBox}>
                    <Text style={styles.strategyLabel}>Strategy:</Text>
                    <Text style={styles.strategyText}>{aiAnalysis.teachingStrategy}</Text>
                  </View>
                )}
              </View>
            )}
          </View>
        )}

        {/* Empty state */}
        {!hasContent && (
          <View style={styles.emptyState}>
            <Text style={styles.emptyEmoji}>🎯</Text>
            <Text style={styles.emptyTitle}>No Practice Needed Yet</Text>
            <Text style={styles.emptyDesc}>
              Complete some lessons and the system will automatically detect areas where you need extra practice. It's like having a teacher who always knows what you need to work on.
            </Text>
            <Pressable
              onPress={() => router.push("/(tabs)" as any)}
              style={({ pressed }) => [styles.goLearnBtn, pressed && { opacity: 0.8 }]}
            >
              <Text style={styles.goLearnBtnText}>Go Learn Something</Text>
            </Pressable>
          </View>
        )}

        {/* Student Profile Summary */}
        {profile && profile.totalExercisesCompleted > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>📊 Your Profile</Text>
            <View style={styles.profileCard}>
              <View style={styles.profileStat}>
                <Text style={styles.profileStatValue}>{profile.overallAccuracy}%</Text>
                <Text style={styles.profileStatLabel}>Overall Accuracy</Text>
              </View>
              <View style={styles.profileStat}>
                <Text style={styles.profileStatValue}>{profile.totalExercisesCompleted}</Text>
                <Text style={styles.profileStatLabel}>Exercises Done</Text>
              </View>
              <View style={styles.profileStat}>
                <Text style={styles.profileStatValue}>{profile.weakAreas.length}</Text>
                <Text style={styles.profileStatLabel}>Weak Areas</Text>
              </View>
            </View>
          </View>
        )}
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { fontSize: 16, color: "#9BA1A6", marginTop: 12 },
  header: { padding: 20, paddingTop: 12 },
  backBtn: { fontSize: 14, color: "#00AAFF", marginBottom: 12 },
  title: { fontSize: 28, fontWeight: "800", color: "#ECEDEE", marginBottom: 4 },
  subtitle: { fontSize: 14, color: "#9BA1A6" },
  section: { paddingHorizontal: 20, marginTop: 24 },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: "#ECEDEE", marginBottom: 4 },
  sectionDesc: { fontSize: 13, color: "#9BA1A6", marginBottom: 12 },

  // Insights
  insightCard: { backgroundColor: "#1a2234", borderRadius: 12, padding: 14, marginBottom: 10, borderLeftWidth: 3, borderLeftColor: "#00AAFF" },
  insightCardUrgent: { borderLeftColor: "#EF4444" },
  insightHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  insightTitle: { fontSize: 14, fontWeight: "700", color: "#ECEDEE", flex: 1 },
  dismissBtn: { fontSize: 16, color: "#9BA1A6", padding: 4 },
  insightMessage: { fontSize: 13, color: "#9BA1A6", marginTop: 6, lineHeight: 18 },
  insightAction: { marginTop: 10, backgroundColor: "#00AAFF", borderRadius: 8, paddingVertical: 8, paddingHorizontal: 14, alignSelf: "flex-start" },
  insightActionText: { fontSize: 12, fontWeight: "700", color: "#fff" },

  // Homework
  homeworkCard: { backgroundColor: "#1a2234", borderRadius: 14, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: "#334155" },
  homeworkOverdue: { borderColor: "#EF4444" },
  homeworkHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  homeworkTitle: { fontSize: 16, fontWeight: "700", color: "#ECEDEE", flex: 1 },
  homeworkDesc: { fontSize: 13, color: "#9BA1A6", marginBottom: 6, lineHeight: 18 },
  homeworkAssigner: { fontSize: 11, color: "#687076", marginBottom: 12 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  badgeBlue: { backgroundColor: "rgba(0,170,255,0.15)" },
  badgeRed: { backgroundColor: "rgba(239,68,68,0.15)" },
  badgeText: { fontSize: 10, fontWeight: "600", color: "#00AAFF" },
  progressBarContainer: { height: 4, backgroundColor: "#0a1628", borderRadius: 2, marginBottom: 6 },
  progressBar: { height: 4, backgroundColor: "#22C55E", borderRadius: 2 },
  progressText: { fontSize: 11, color: "#687076", marginBottom: 10 },
  exerciseItem: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderTopWidth: 0.5, borderTopColor: "#334155" },
  exerciseCompleted: { opacity: 0.6 },
  exerciseIcon: { fontSize: 16, marginRight: 10 },
  exerciseTitle: { fontSize: 14, color: "#ECEDEE", fontWeight: "500" },
  exerciseTitleDone: { textDecorationLine: "line-through", color: "#687076" },
  exerciseType: { fontSize: 11, color: "#687076", marginTop: 2 },
  exerciseAccuracy: { fontSize: 12, color: "#22C55E", fontWeight: "600", marginRight: 8 },
  exerciseArrow: { fontSize: 16, color: "#00AAFF" },

  // Recommendations
  recCard: { backgroundColor: "#1a2234", borderRadius: 12, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: "#334155" },
  recCardCritical: { borderColor: "#EF4444", borderWidth: 1.5 },
  recHeader: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  urgencyDot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
  urgency_low: { backgroundColor: "#22C55E" },
  urgency_medium: { backgroundColor: "#F59E0B" },
  urgency_high: { backgroundColor: "#F97316" },
  urgency_critical: { backgroundColor: "#EF4444" },
  recTitle: { fontSize: 14, fontWeight: "700", color: "#ECEDEE", flex: 1 },
  recTime: { fontSize: 11, color: "#687076" },
  recDescription: { fontSize: 13, color: "#9BA1A6", marginBottom: 4 },
  recReason: { fontSize: 11, color: "#687076", fontStyle: "italic", marginBottom: 10 },
  recActions: { flexDirection: "row", gap: 10 },
  startBtn: { backgroundColor: "#00AAFF", borderRadius: 8, paddingVertical: 8, paddingHorizontal: 16 },
  startBtnText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  skipBtn: { paddingVertical: 8, paddingHorizontal: 12 },
  skipBtnText: { fontSize: 13, color: "#9BA1A6" },

  // Struggles
  struggleItem: { backgroundColor: "#1a2234", borderRadius: 10, padding: 12, marginBottom: 8 },
  struggleHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  struggleTopic: { fontSize: 14, fontWeight: "600", color: "#ECEDEE" },
  severityBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  severityRed: { backgroundColor: "rgba(239,68,68,0.2)" },
  severityOrange: { backgroundColor: "rgba(249,115,22,0.2)" },
  severityYellow: { backgroundColor: "rgba(245,158,11,0.2)" },
  severityText: { fontSize: 10, fontWeight: "600", color: "#F59E0B" },
  struggleStats: { flexDirection: "row", gap: 12, marginTop: 6 },
  struggleStat: { fontSize: 11, color: "#9BA1A6" },
  struggleTrend: { fontSize: 11, fontWeight: "600" },
  trendGreen: { color: "#22C55E" },
  trendRed: { color: "#EF4444" },
  trendGray: { color: "#9BA1A6" },

  // AI Analysis
  aiAnalysisBtn: { backgroundColor: "#6366F1", borderRadius: 10, paddingVertical: 12, alignItems: "center", marginTop: 12 },
  aiAnalysisBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },
  aiResultCard: { backgroundColor: "#1a1a2e", borderRadius: 12, padding: 16, marginTop: 12, borderWidth: 1, borderColor: "#6366F1" },
  aiResultTitle: { fontSize: 15, fontWeight: "700", color: "#A78BFA", marginBottom: 8 },
  aiEncouragement: { fontSize: 14, color: "#ECEDEE", lineHeight: 20, marginBottom: 12 },
  aiPracticeItem: { backgroundColor: "rgba(99,102,241,0.1)", borderRadius: 8, padding: 10, marginBottom: 6 },
  aiPracticeTitle: { fontSize: 13, fontWeight: "600", color: "#ECEDEE" },
  aiPracticeDesc: { fontSize: 12, color: "#9BA1A6", marginTop: 2 },
  strategyBox: { marginTop: 10, paddingTop: 10, borderTopWidth: 0.5, borderTopColor: "#334155" },
  strategyLabel: { fontSize: 11, fontWeight: "700", color: "#A78BFA", marginBottom: 4 },
  strategyText: { fontSize: 12, color: "#9BA1A6", lineHeight: 18 },

  // Empty state
  emptyState: { alignItems: "center", paddingTop: 80, paddingHorizontal: 40 },
  emptyEmoji: { fontSize: 48, marginBottom: 16 },
  emptyTitle: { fontSize: 20, fontWeight: "700", color: "#ECEDEE", marginBottom: 8 },
  emptyDesc: { fontSize: 14, color: "#9BA1A6", textAlign: "center", lineHeight: 20, marginBottom: 24 },
  goLearnBtn: { backgroundColor: "#00AAFF", borderRadius: 10, paddingVertical: 12, paddingHorizontal: 24 },
  goLearnBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  // Profile
  profileCard: { flexDirection: "row", justifyContent: "space-around", backgroundColor: "#1a2234", borderRadius: 12, padding: 16, marginTop: 8 },
  profileStat: { alignItems: "center" },
  profileStatValue: { fontSize: 22, fontWeight: "800", color: "#00AAFF" },
  profileStatLabel: { fontSize: 11, color: "#9BA1A6", marginTop: 4 },

  // Spaced Repetition
  srsHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4 },
  srsStatsRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  srsStatText: { fontSize: 11, color: "#687076" },
  srsStatDivider: { fontSize: 8, color: "#687076" },
  srsCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#1a2234", borderRadius: 12, padding: 14, marginBottom: 8, borderLeftWidth: 3, borderLeftColor: "#8B5CF6" },
  srsCardLeft: { flex: 1 },
  srsCardTopic: { fontSize: 14, fontWeight: "700", color: "#ECEDEE" },
  srsCardSubtopic: { fontSize: 12, color: "#9BA1A6", marginTop: 2 },
  srsCardMeta: { flexDirection: "row", alignItems: "center", marginTop: 6, gap: 6 },
  srsCardType: { fontSize: 11, color: "#8B5CF6", fontWeight: "500" },
  srsCardDot: { fontSize: 8, color: "#687076" },
  srsCardInterval: { fontSize: 11, color: "#687076" },
  srsCardAccuracy: { fontSize: 11, color: "#22C55E" },
  srsCardArrow: { fontSize: 18, color: "#8B5CF6" },
  srsMoreText: { fontSize: 12, color: "#687076", textAlign: "center", marginTop: 4 },
  srsNextCard: { backgroundColor: "#1a2234", borderRadius: 12, padding: 16, marginTop: 8 },
  srsNextMessage: { fontSize: 14, color: "#ECEDEE", fontWeight: "500" },
  srsNextCount: { fontSize: 12, color: "#9BA1A6", marginTop: 4 },
  // Gamification styles
  gamBar: { marginHorizontal: 20, backgroundColor: "#1E2030", borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: "#2A2D3E" },
  gamRow: { flexDirection: "row", justifyContent: "space-around", marginBottom: 12 },
  gamStat: { alignItems: "center" },
  gamIcon: { fontSize: 20, marginBottom: 2 },
  gamValue: { fontSize: 16, fontWeight: "800", color: "#ECEDEE" },
  gamLabel: { fontSize: 10, color: "#9BA1A6", marginTop: 2 },
  xpBarContainer: { marginTop: 4 },
  xpBarBg: { height: 6, backgroundColor: "#2A2D3E", borderRadius: 3, overflow: "hidden" },
  xpBarFill: { height: "100%", backgroundColor: "#8B5CF6", borderRadius: 3 },
  xpBarText: { fontSize: 10, color: "#9BA1A6", textAlign: "center", marginTop: 4 },
  perfectBadge: { backgroundColor: "#22C55E20", borderRadius: 8, padding: 8, marginTop: 8, alignItems: "center" },
  perfectBadgeText: { fontSize: 12, color: "#22C55E", fontWeight: "700" },
  xpPopup: { position: "absolute", top: 120, left: 20, right: 20, backgroundColor: "#8B5CF6", borderRadius: 12, padding: 14, alignItems: "center", zIndex: 100, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 8 },
  xpPopupText: { fontSize: 14, fontWeight: "700", color: "#fff" },
  xpPopupBadge: { fontSize: 12, color: "#FFD700", marginTop: 4, fontWeight: "600" },
});
